---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 6.32.14
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 5m
  values:
    admin:
      existingSecret: grafana-admin-creds
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - disableDeletion: false
            editable: true
            folder: ""
            name: default
            options:
              path: /var/lib/grafana/dashboards/default
            orgId: 1
            type: file
    dashboards:
      default:
        calico-felix:
          datasource: Prometheus
          gnetId: 12175
          revision: 5
        flux-cluster:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
        flux-control-plane:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
        loki-logs:
          datasource: Loki
          gnetId: 12019
          revision: 2
        speedtest:
          datasource: Prometheus
          gnetId: 13665
          revision: 1
        traefik-ingress:
          datasource: Prometheus
          gnetId: 4475
          revision: 5
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - access: proxy
            isDefault: true
            name: Prometheus
            type: prometheus
            url: http://thanos-query:9090
          - access: proxy
            name: Loki
            type: loki
            url: http://loki:3100
        deleteDatasources:
          - name: Loki
            orgId: 1
    deploymentStrategy:
      type: Recreate
    env:
      GF_DATE_FORMATS_FULL_DATE: MMM Do, YYYY hh:mm:ss a
      GF_DATE_FORMATS_INTERVAL_DAY: DD/MM
      GF_DATE_FORMATS_INTERVAL_HOUR: DD/MM hh:mm a
      GF_DATE_FORMATS_INTERVAL_MINUTE: hh:mm a
      GF_DATE_FORMATS_INTERVAL_MONTH: MM-YYYY
      GF_DATE_FORMATS_INTERVAL_SECOND: hh:mm:ss a
      GF_DATE_FORMATS_INTERVAL_YEAR: YYYY
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_EXPLORE_ENABLED: true
      GF_LOG_FILTERS: rendering:debug
      GF_PANELS_DISABLE_SANITIZE_HTML: true
    grafana.ini:
      analytics:
        check_for_updates: false
      auth:
        oauth_auto_login: true
      auth.basic:
        disable_login_form: false
      # auth.google:
        # allow_sign_up: true
        # client_id: ${SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_ID}
        # client_secret: ${SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_SECRET}
        # enabled: true
        # scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      grafana_net:
        url: https://grafana.net
      log:
        mode: console
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      server:
        enable_gzip: true
        root_url: https://grafana.${SECRET_DOMAIN}
      users:
        allow_sign_up: false
        auto_assign_org_role: Admin
        viewers_can_edit: true
    persistence:
      enabled: true
      type: pvc
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 4Gi
      finalizers:
        - kubernetes.io/pvc-protection
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    podAnnotations:
      configmap.reloader.stakater.com/reload: grafana
    replicas: 1
    serviceAccount:
      autoMount: true
      create: true
    serviceMonitor:
      enabled: true
    # tolerations:
    #   - key: "node.kubernetes.io/unreachable"
    #     operator: "Exists"
    #     effect: "NoExecute"
    #     # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
    #     tolerationSeconds: 15
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "grafana.${SECRET_DOMAIN}"
          secretName: grafana
