---
apiversion: helm.toolkit.fluxcd.io/v2
kind: helmrelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.15.6
      sourceref:
        kind: helmrepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanuponfail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csi:
      cephfskernelmountoptions: ms_mode=prefer-crc
      enableliveness: true
      servicemonitor:
        enabled: true
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m # unchangable
        memory: 128mi # unchangable
      limits: {}
