---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./botkube/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./unifi-poller/ks.yaml
  - ./goldilocks/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./gatus/ks.yaml
  # - thanos
