---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft-secret
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.2.0-java21
    resources:
      limits:
        memory: 16Gi
      requests:
        cpu: 1000m
        memory: 15Gi
    securityContext:
      runAsUser: 1000
    podSecurityContext:
      fsGroup: 2000
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
      kubernetes.io/hostname: k8s-2
    livenessProbe:
      command:
        - mc-health
      initialDelaySeconds: 60
      periodSeconds: 10
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      command:
        - mc-health
      initialDelaySeconds: 45
      periodSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 5
    startupProbe:
      command:
        - mc-health
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 30
      timeoutSeconds: 5
    extraEnv:
      GENERATE_LOG4J2_CONFIG: true # https://github.com/itzg/docker-minecraft-server/issues/3857
      TZ: "Europe/Paris"
      UID: 1000
      GID: 2000
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      lbipam.cilium.io/ips: "192.168.69.102"
    serviceLabels:
      io.cilium/ippool: public
    minecraftServer:
      eula: true
      # renovate: datasource=custom.minecraft-release
      version: 1.21.11
      type: FABRIC
      difficulty: normal
      whitelist: "Speeddrat,Anty0,phonyAustralian,TheHnatekmar,DemTriangles,MountHelen1980,Morgoth_the_3rd,CrazyRogueE" # Pridat bioaldu
      ops: "phonyAustralian,DemTriangles"
      pvp: true
      motd: Meh
      worldSaveName: "The Forgotten Realm"
      viewDistance: 16
      forceReDownload: true
      memory: 14G
      jvmXXOpts: "-XX:+UseZGC -XX:+ZGenerational -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch"
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      spigetResources:
        - 36618
      spigotConfig: |
        settings:
          timeout-time: 90
        world-settings:
          default:
            max-tick-time:
              tile: 1000
              entity: 1000
      serverProperties: |
        network-compression-threshold=512
        max-tick-time=60000
        player-idle-timeout=30
      extraPorts:
        - name: map
          containerPort: 8100
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8100
      modrinth:
        projects:
          - worldedit
          - ferrite-core
          - lithium
          - distanthorizons:beta
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password
