---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecraft-restart
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["minecraft"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/status"]
    resourceNames: ["minecraft"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecraft-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minecraft-restart
subjects:
  - kind: ServiceAccount
    name: minecraft-restart
