---
# (string) Timezone for the servers
timezone: "Europe/Paris"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

fedora:
  packages:
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - intel-gpu-tools
    - ipvsadm
    - lm_sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-yaml

ubuntu:
  # disable_ufw: true
  # disable_swap: true
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
