---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: devices
spec:
  module: icmp
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      targets:
        - nas.internal
        - db.internal
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: nfs
spec:
  module: tcp_connect
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      targets:
        - nas.internal:2049
