# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: "kubernetes"

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.69.254:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.69.254"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-0"
    ipAddress: "192.168.69.110"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/44094505f553b2341580d87c83653f3aa5cbef305443e9b981236cb66396b31d
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:80:71:13"
        dhcp: false
        addresses:
          - "192.168.69.110/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.69.1"
        mtu: 1500
        vip:
          ip: "192.168.69.254"
  - hostname: "k8s-1"
    ipAddress: "192.168.69.111"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/96f8c146a67c80daad900d3fc1a6976fe11062321eee9ab6ae2a6aea88b2d26e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:c0:08:9b:2b:e6"
        dhcp: false
        addresses:
          - "192.168.69.111/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.69.1"
        mtu: 1500
  - hostname: "k8s-2"
    ipAddress: "192.168.69.112"
    installDisk: "/dev/sda"
    extraManifests:
      - ./manifests/e1000e.yaml
    talosImageURL: factory.talos.dev/installer/2d61dd07b20062062ea671b4d01873506103b67c0f7a4c3fb6cf4ee85585dcb8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "1c:69:7a:0a:1e:55"
        dhcp: false
        addresses:
          - "192.168.69.112/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.69.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/apiserver-resources.yaml"
