---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./victoria-metrics/ks.yaml
  - ./kromgo/ks.yaml
  - ./coroot/ks.yaml
  - ./gatus/ks.yaml
  - ./keda/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./grafana/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  # - ./victoria-logs/ks.yaml
  # I should remove these?
  # - ./kube-prometheus-stack/ks.yaml
  # - ./karma/ks.yaml
  # - ./loki/ks.yaml
  # - ./alloy/ks.yaml
  # - ./unpoller/ks.yaml
  # - ./silence-operator/ks.yaml
