---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  # - ./prometheus-operator-crds/ks.yaml
  # - ./kube-prometheus-stack/ks.yaml
  # - ./kromgo/ks.yaml
  # - ./karma/ks.yaml
  - ./gatus/ks.yaml
  # - ./grafana/ks.yaml
  # - ./loki/ks.yaml
