---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
