---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./backube.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./external-secrets.yaml
  - ./democratic-csi.yaml
  - ./grafana.yaml
