---
collections:
  - name: community.general
    version: 9.5.0
  - name: community.sops
    version: 1.9.1
  - name: ansible.posix
    version: 1.6.1
  - name: ansible.utils
    version: 5.1.2
  - name: kubernetes.core
    version: 5.0.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.4
