---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-rook-ceph-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/rook-ceph/rook-ceph/operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-rook-ceph-cluster
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/rook-ceph/rook-ceph/cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-rook-ceph-operator
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-rook-ceph-dashboard
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/rook-ceph/rook-ceph/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
