---
k3s_control_node: true
k3s_server:
  cluster-cidr: "10.69.0.0/16"
  service-cidr: "10.96.0.0/16"
  disable: ["flannel", "local-storage", "metrics-server", "servicelb", "traefik"]
  disable-cloud-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  docker: false
  embedded-registry: true
  etcd-expose-metrics: true
  flannel-backend: "none"
  kube-apiserver-arg:
    - "anonymous-auth=true"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  node-ip: "{{ ansible_host }}"
  secrets-encryption: true
  tls-san: "192.168.69.254"
  write-kubeconfig-mode: "644"
  datastore-endpoint: "{{ database_endpoint }}"
