---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: volsync
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncComponentAbsent
          expr: |-
            absent(up{job="volsync-metrics"})
          annotations:
            summary: >-
              VolSync component has disappeared from Prometheus target discovery
          for: 5m
          labels:
            severity: critical

        - alert: VolSyncVolumeOutOfSync
          expr: |-
            volsync_volume_out_of_sync == 1
          annotations:
            summary: >-
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} volume is out of sync
          for: 5m
          labels:
            severity: critical
